name: orderkuy_kasir
description: Aplikasi kasir OrderKuy
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP & Network
  http: ^1.1.0

  # Local Storage
  shared_preferences: ^2.2.2

  # Permissions
  permission_handler: ^11.3.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_thermal_printer: ^1.2.4
  image: ^4.5.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  assets:
    - assets/icon/orderkuy.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/orderkuy.png"
